apiVersion: v1 
kind: Deployment
metadata:
    name: cloud7-employeeapp-backend-deployment
    labels:
      name: cloud7-employeeapp-backend-deployment
spec:
  selector:
    name: cloud7-employeeapp-backend-deployment
  
  template:
    metadata:
      name: cloud7-employeeapp-backend-deployment
    spec:
      containers:
      - name: node
        image: jayashreeumale/cloud7-nodeapp
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: DBHOST
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: DBNAME
        ports:
        - name: backend
          containerPort: 3002
          protocol: TCP