apiVersion: v1
kind: Service
metadata:
  name: cloud7-employeeapp-backend-service
spec:
  type: NodePort
  ports:
    - targetPort: 3002
      port: 3002
      nodePort: 30008
  selector:
    name: cloud7-employeeapp-backend-deployment