apiVersion: v1
kind: PersistentVolume
metadata:
  name: cloud7-employeeapp-pv
spec:
  capacity: 
    storage: 2Gi
  storageClassName: standard
  gcePersistentDisk:
    fsType: ext4
    pdName: disk-1
  accessModes:
    - ReadWriteOnce
    