apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud7-employeeapp-pvc
  labels:
    app: cloud7-employeeapp-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
 